# Generated by Django 3.1.3 on 2022-09-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0002_auto_20220918_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardselling',
            name='groupno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boardselling',
            name='orderno',
            field=models.IntegerField(default=0),
        ),
    ]
