# Generated by Django 3.1.3 on 2022-09-19 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0003_auto_20220919_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lacal',
            name='metro_idx',
        ),
        migrations.RemoveField(
            model_name='qnasubcategory',
            name='aq_mcategory',
        ),
        migrations.RemoveField(
            model_name='report',
            name='member_idx',
        ),
        migrations.RemoveField(
            model_name='boardselling',
            name='price_propose',
        ),
        migrations.DeleteModel(
            name='BoardNotice',
        ),
        migrations.DeleteModel(
            name='Lacal',
        ),
        migrations.DeleteModel(
            name='Metro',
        ),
        migrations.DeleteModel(
            name='QnaSubCategory',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
