# Generated by Django 3.1.3 on 2022-09-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddm', '0004_auto_20220919_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardselling',
            name='groupno',
        ),
        migrations.RemoveField(
            model_name='boardselling',
            name='orderno',
        ),
        migrations.RemoveField(
            model_name='qna',
            name='admin_idx',
        ),
        migrations.DeleteModel(
            name='AdminMember',
        ),
    ]
